server:
  port: 8080
  servlet:
    context-path: "/volleyball-fashion"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/volfas_store"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
