server:
  port: 8080
  servlet:
    context-path: "/volleyball-fashion"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/volfas_store"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "wGmqW/XEi37eAiw3LjBMwpiKr1U/QxJ7/8rJQvg4mXE6RTKdbPxJpcX7K2HybN8k"